/** Textos públicos PT/EN revisados na etapa 17. */
const pt = {
  nav: {
    about: "Sobre",
    projects: "Projetos",
    education: "Formação",
    datanogs: "DataNogs",
    experience: "Experiência",
    contact: "Contato",
    cta: "Vamos conversar",
    home: "início",
    main: "Navegação principal",
    mobile: "Navegação mobile",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    skip: "Pular para o conteúdo",
  },
  prefs: {
    language: "Idioma",
    theme: "Tema",
    toDark: "Ativar tema escuro",
    toLight: "Ativar tema claro",
    dark: "Escuro",
    light: "Claro",
    switchTo: "Mudar idioma para",
  },
  home: {
    exploreProjects: "Explorar projetos",
    mainStack: "Stack principal",
    studying: "Em estudo: SQL · Python",
    quickNav: "Explore minha trajetória",
    toolsLink: "Ferramentas",
    aboutEyebrow: "Sobre mim",
    aboutTitle: "Da Logística aos Dados",
    aboutLink: "Conheça minha trajetória",
    stackEyebrow: "Stack",
    stackTitle: "Ferramentas e contexto de uso",
    stackDescription:
      "Os cases mostram a prática em BI; a rotina administrativa e os estudos complementam essa base.",
    projectsEyebrow: "Portfólio",
    projectsTitle: "Projetos selecionados",
    featured: "Projeto em destaque",
    allProjects: "Ver todos os projetos",
    experienceEyebrow: "Trajetória",
    experienceTitle: "Experiência",
    experienceDescription: "Compras, sistemas de gestão e indicadores no setor de transporte.",
    educationEyebrow: "Formação",
    educationTitle: "Logística, Supply Chain e Computação",
    educationDescription:
      "CST em Logística e MBA em Supply Chain Management concluídos; Ciência da Computação em andamento.",
    certificationsEyebrow: "Certificações",
    certificationsTitle: "Estudos que ampliam a prática",
    certificationsDescription:
      "Cursos de Excel, Power BI, Power Query, DAX, SQL e temas de inteligência artificial complementam minha formação.",
    certificationsEmpty: "Nenhum certificado publicado nesta versão.",
    datanogsEyebrow: "Projeto autoral",
    datanogsTitle: "DataNogs",
    datanogsDescription:
      "Meu projeto autoral para compartilhar minha trajetória em Dados por meio de estudos, projetos e explicações.",
    ctaEyebrow: "Próximo passo",
    ctaTitle: "Veja os cases ou fale comigo.",
    ctaDescription:
      "O portfólio é uma visão do processo. Os cases mostram como cada análise foi estruturada.",
    contactEyebrow: "Contato",
    contactTitle: "Vamos conversar?",
    contactChannels: "Ver canais de contato",
    analysisFlow: {
      label: "Estrutura de análise",
      steps: ["Fonte", "Tratamento", "Modelagem", "Análise", "Comunicação"],
      footer: "Processo antes de interface",
    },
  },
  experience: {
    activities: "Principais atividades",
    dataWork: "Indicadores e ferramentas de dados",
  },
  about: {
    eyebrow: "Sobre",
    experienceEyebrow: "Trajetória",
    experienceTitle: "Experiência",
    educationEyebrow: "Formação",
    educationTitle: "Formação acadêmica",
    educationDescription:
      "Formação concluída em Logística e Supply Chain, com estudos atuais em Ciência da Computação.",
    seeProjects: "Ver projetos",
  },
  certifications: {
    pageEyebrow: "Formação",
    pageTitle: "Formação e Certificações",
    pageDescription:
      "Minha base acadêmica reúne Logística e Supply Chain. Os estudos em Ciência da Computação e os cursos de dados complementam essa trajetória.",
    academicLabel: "Formações acadêmicas",
    certificatesLabel: "Certificados",
    sourceLabel: "Documentos",
    sourceValue: "Certificados disponíveis em PDF.",
    libraryEyebrow: "Biblioteca",
    libraryTitle: "Certificações",
    libraryDescription:
      "Consulte cursos, instituições, datas e cargas horárias. Os PDFs estão disponíveis para visualização.",
    search: "Buscar",
    searchPlaceholder: "Curso, instituição, tecnologia ou tema",
    category: "Categoria",
    technology: "Tecnologia",
    all: "Todos",
    workload: "Carga horária",
    technologies: "Tecnologias",
    preview: "Visualizar",
    openPdf: "Abrir PDF",
    close: "Fechar visualização",
    clear: "Limpar filtros",
    empty: "Nenhum certificado corresponde aos filtros atuais.",
    resultSingular: "certificado",
    resultPlural: "certificados",
    seeAll: "Ver formação e certificados",
  },
  projects: {
    eyebrow: "Portfólio",
    title: "Projetos e cases",
    featured: "Projeto em destaque",
    viewCase: "Ver case",
    coverPlaceholder: "Imagem de capa",
    coverAlt: "Capa do projeto",
    dashboardPlaceholder: "Imagem do dashboard principal",
    dashboardAlt: "Dashboard do projeto",
    libraryEyebrow: "Arquivo de projetos",
    libraryTitle: "Explore por categoria ou tecnologia",
    libraryDescription:
      "Compare projetos de música, vendas e abastecimentos e explore o processo técnico de cada um.",
    filterCategory: "Categoria",
    filterTechnology: "Tecnologia",
    filterAll: "Todos",
    resultSingular: "projeto",
    resultPlural: "projetos",
    clearFilters: "Limpar filtros",
    noResults: "Nenhum projeto corresponde aos filtros selecionados.",
    ctaEyebrow: "Contato",
    ctaTitle: "Quer conversar sobre algum dos cases?",
    ctaDescription:
      "Você pode abrir os relatórios no Power BI a partir dos cases ou falar comigo para discutir sua construção.",
  },
  project: {
    contents: "Neste case",
    back: "Todos os projetos",
    dashboard: "Dashboard público",
    heroPlaceholder: "Imagem principal do projeto",
    heroAlt: "Visão geral do projeto",
    context: "Contexto",
    problem: "Pergunta analítica",
    objective: "Objetivo",
    data: "Fontes e estrutura dos dados",
    dataSource: "Fonte identificada",
    dataEntities: "Tabelas / entidades",
    dataFields: "Campos observados",
    treatment: "Tratamento",
    transformation: "Transformação",
    model: "Modelagem",
    metrics: "Métricas",
    tools: "Tecnologias",
    explore: "Dashboard",
    dashboardPages: "Páginas",
    gallery: "Galeria do relatório",
    openImage: "Abrir imagem",
    openDashboard: "Abrir no Power BI",
    insights: "Análises e observações",
    results: "Resultado técnico",
    learnings: "Competências demonstradas",
    overview: "Visão do projeto",
    dataModel: "Dados e modelagem",
    viewFormula: "Ver fórmula DAX",
    observations: "O que as imagens mostram",
    challenges: "Desafios analíticos e soluções observadas",
    limitations: "Limites de interpretação",
    github: "GitHub",
    youtube: "YouTube",
    continue: "Continue",
    others: "Outros projetos",
  },
  datanogsPage: {
    identity: "Identidade",
    professional: "Identidade profissional",
    project: "Projeto autoral",
    distinction: "Papéis diferentes, uma mesma trajetória",
    scope: "Temas",
    scopeTitle: "Temas de estudo",
    presence: "Presença digital",
    presenceTitle: "Onde acompanhar",
    presenceDescription:
      "A proposta prioriza YouTube para vídeo e GitHub para código e materiais. O contato profissional está no LinkedIn.",
    visit: "Acessar",
    portfolio: "Portfólio profissional",
    portfolioTitle: "Conheça os projetos em detalhe.",
    portfolioDescription:
      "Os cases deste portfólio reúnem modelagem, medidas e análises dos dashboards desenvolvidos em Power BI.",
    professionalDescription:
      "É a identidade principal deste portfólio e da minha presença profissional.",
    viewProjects: "Ver projetos",
    contact: "Contato",
  },
  contact: {
    eyebrow: "Contato",
    title: "Vamos conversar?",
    open: "Abrir",
    copy: "Copiar",
    copied: "Copiado!",
    copyEmail: "Copiar e-mail",
    copyError: "Não foi possível copiar automaticamente. Selecione o endereço acima para copiar.",
  },
  footer: {
    navigation: "Navegação",
    channels: "Canais",
    lastUpdate: "Última atualização",
    pending: "link pendente",
    backToTop: "Voltar ao topo",
  },
  common: {
    pending: "link pendente",
    inProgress: "Conteúdo em desenvolvimento",
    profilePhotoAlt: "Retrato profissional de João Vittor Nogueira",
    opensNewTab: "abre em uma nova aba",
  },
  notFound: {
    title: "Página não encontrada",
    text: "A página que você procura não existe ou foi movida.",
    home: "Voltar ao início",
  },
  error: {
    title: "Esta página não carregou",
    text: "Algo deu errado. Tente novamente ou volte ao início.",
    retry: "Tentar novamente",
    home: "Voltar ao início",
  },
};
export type UiDict = typeof pt;
const en: UiDict = {
  nav: {
    about: "About",
    projects: "Projects",
    education: "Education",
    datanogs: "DataNogs",
    experience: "Experience",
    contact: "Contact",
    cta: "Let's talk",
    home: "home",
    main: "Main navigation",
    mobile: "Mobile navigation",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    skip: "Skip to content",
  },
  prefs: {
    language: "Language",
    theme: "Theme",
    toDark: "Switch to dark theme",
    toLight: "Switch to light theme",
    dark: "Dark",
    light: "Light",
    switchTo: "Switch language to",
  },
  home: {
    exploreProjects: "Explore projects",
    mainStack: "Core stack",
    studying: "Currently studying: SQL · Python",
    quickNav: "Explore my background",
    toolsLink: "Tools",
    aboutEyebrow: "About me",
    aboutTitle: "From Logistics to Data",
    aboutLink: "Read my story",
    stackEyebrow: "Stack",
    stackTitle: "Tools and how I use them",
    stackDescription:
      "The case studies show my BI practice; administrative work and ongoing studies complement this foundation.",
    projectsEyebrow: "Portfolio",
    projectsTitle: "Selected work",
    featured: "Featured project",
    allProjects: "View all projects",
    experienceEyebrow: "Career",
    experienceTitle: "Experience",
    experienceDescription: "Purchasing, management systems and indicators in transportation.",
    educationEyebrow: "Education",
    educationTitle: "Logistics, Supply Chain and Computing",
    educationDescription:
      "Completed Technology Degree in Logistics and MBA in Supply Chain Management; Computer Science in progress.",
    certificationsEyebrow: "Certifications",
    certificationsTitle: "Learning that supports practice",
    certificationsDescription:
      "Courses in Excel, Power BI, Power Query, DAX, SQL and artificial intelligence complement my education.",
    certificationsEmpty: "No certificate has been published in this version.",
    datanogsEyebrow: "Personal project",
    datanogsTitle: "DataNogs",
    datanogsDescription:
      "My personal project for sharing my journey in Data through studies, projects and explanations.",
    ctaEyebrow: "Next step",
    ctaTitle: "Explore the case studies or get in touch.",
    ctaDescription:
      "The portfolio shows the process at a glance. The case studies show how each analysis was structured.",
    contactEyebrow: "Contact",
    contactTitle: "Let’s talk",
    contactChannels: "See contact channels",
    analysisFlow: {
      label: "Analysis structure",
      steps: ["Source", "Transform", "Model", "Analyze", "Communicate"],
      footer: "Process before interface",
    },
  },
  experience: {
    activities: "Key responsibilities",
    dataWork: "Indicators and data tools",
  },
  about: {
    eyebrow: "About",
    experienceEyebrow: "Career",
    experienceTitle: "Experience",
    educationEyebrow: "Education",
    educationTitle: "Academic background",
    educationDescription:
      "Completed education in Logistics and Supply Chain, alongside current Computer Science studies.",
    seeProjects: "View projects",
  },
  certifications: {
    pageEyebrow: "Education",
    pageTitle: "Education & Certifications",
    pageDescription:
      "My academic background brings together Logistics and Supply Chain. Computer Science studies and data courses complement this path.",
    academicLabel: "Academic programs",
    certificatesLabel: "Certificates",
    sourceLabel: "Documents",
    sourceValue: "Certificates available as PDFs.",
    libraryEyebrow: "Library",
    libraryTitle: "Certifications",
    libraryDescription:
      "Browse courses, institutions, dates and study hours. The certificate PDFs are available to view.",
    search: "Search",
    searchPlaceholder: "Course, institution, technology or topic",
    category: "Category",
    technology: "Technology",
    all: "All",
    workload: "Workload",
    technologies: "Technologies",
    preview: "Preview",
    openPdf: "Open PDF",
    close: "Close preview",
    clear: "Clear filters",
    empty: "No certificate matches the current filters.",
    resultSingular: "certificate",
    resultPlural: "certificates",
    seeAll: "View education and certificates",
  },
  projects: {
    eyebrow: "Portfolio",
    title: "Projects and case studies",
    featured: "Featured project",
    viewCase: "View case study",
    coverPlaceholder: "Cover image",
    coverAlt: "Cover of project",
    dashboardPlaceholder: "Main dashboard image",
    dashboardAlt: "Dashboard of project",
    libraryEyebrow: "Project archive",
    libraryTitle: "Explore by category or technology",
    libraryDescription:
      "Compare music, sales and refueling projects and explore the technical process behind each one.",
    filterCategory: "Category",
    filterTechnology: "Technology",
    filterAll: "All",
    resultSingular: "project",
    resultPlural: "projects",
    clearFilters: "Clear filters",
    noResults: "No project matches the selected filters.",
    ctaEyebrow: "Contact",
    ctaTitle: "Want to discuss one of the case studies?",
    ctaDescription:
      "You can open the Power BI reports from the case studies or contact me to discuss how they were built.",
  },
  project: {
    contents: "In this case study",
    back: "All projects",
    dashboard: "Public dashboard",
    heroPlaceholder: "Main project image",
    heroAlt: "Overview of project",
    context: "Context",
    problem: "Analytical question",
    objective: "Goal",
    data: "Data sources and structure",
    dataSource: "Identified source",
    dataEntities: "Tables / entities",
    dataFields: "Observed fields",
    treatment: "Data preparation",
    transformation: "Transformation",
    model: "Modeling",
    metrics: "Metrics",
    tools: "Technologies",
    explore: "Dashboard",
    dashboardPages: "Pages",
    gallery: "Report gallery",
    openImage: "Open image",
    openDashboard: "Open in Power BI",
    insights: "Analysis and observations",
    results: "Technical result",
    learnings: "Demonstrated skills",
    overview: "Project overview",
    dataModel: "Data and modeling",
    viewFormula: "View DAX formula",
    observations: "What the images show",
    challenges: "Analytical challenges and observed solutions",
    limitations: "Interpretation limits",
    github: "GitHub",
    youtube: "YouTube",
    continue: "Keep exploring",
    others: "More projects",
  },
  datanogsPage: {
    identity: "Identity",
    professional: "Professional identity",
    project: "Personal project",
    distinction: "Different roles, one journey",
    scope: "Topics",
    scopeTitle: "Study topics",
    presence: "Digital presence",
    presenceTitle: "Where to follow",
    presenceDescription:
      "The plan prioritizes YouTube for video and GitHub for code and materials. LinkedIn is my professional contact channel.",
    visit: "Visit",
    portfolio: "Professional portfolio",
    portfolioTitle: "Explore the projects in detail.",
    portfolioDescription:
      "The case studies in this portfolio bring together modeling, measures and analysis from the Power BI dashboards.",
    professionalDescription:
      "It is the primary identity of this portfolio and my professional presence.",
    viewProjects: "View projects",
    contact: "Contact",
  },
  contact: {
    eyebrow: "Contact",
    title: "Let’s talk",
    open: "Open",
    copy: "Copy",
    copied: "Copied!",
    copyEmail: "Copy email",
    copyError: "Automatic copying is unavailable. Select the address above to copy it.",
  },
  footer: {
    navigation: "Navigation",
    channels: "Channels",
    lastUpdate: "Last updated",
    pending: "link pending",
    backToTop: "Back to top",
  },
  common: {
    pending: "link pending",
    inProgress: "Content in progress",
    profilePhotoAlt: "Professional portrait of João Vittor Nogueira",
    opensNewTab: "opens in a new tab",
  },
  notFound: {
    title: "Page not found",
    text: "The page you're looking for doesn't exist or has been moved.",
    home: "Back to home",
  },
  error: {
    title: "This page didn't load",
    text: "Something went wrong. Try again or head back home.",
    retry: "Try again",
    home: "Back to home",
  },
};
export const ui = { pt, en };
