/** Textos públicos PT/EN. */
const pt = {
  nav: {
    about: "Sobre",
    projects: "Projetos",
    education: "Formação",
    datanogs: "DataNogs",
    experience: "Experiência",
    contact: "Contato",
    cta: "Vamos conversar",
    home: "início",
    main: "Navegação principal",
    mobile: "Navegação mobile",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    skip: "Pular para o conteúdo",
  },
  prefs: {
    language: "Idioma",
    theme: "Tema",
    toDark: "Ativar tema escuro",
    toLight: "Ativar tema claro",
    dark: "Escuro",
    light: "Claro",
    switchTo: "Mudar idioma para",
  },
  home: {
    exploreProjects: "Explorar projetos",
    mainStack: "Stack principal",
    studying: "Em estudo: SQL · Python",
    quickNav: "Conheça meu trabalho",
    toolsLink: "Ferramentas",
    aboutEyebrow: "Sobre mim",
    aboutTitle: "Como penso e trabalho com dados",
    aboutLink: "Mais sobre mim",
    stackEyebrow: "Ferramentas",
    stackTitle: "Da preparação à análise",
    stackDescription:
      "Power Query prepara a base; o modelo e as medidas DAX sustentam a análise; o Power BI organiza a leitura. Veja o que aplico nos projetos e o que estou estudando.",
    projectsEyebrow: "Portfólio",
    projectsTitle: "Projetos selecionados",
    featured: "Projeto em destaque",
    allProjects: "Ver todos os projetos",
    experienceEyebrow: "Trajetória",
    experienceTitle: "Experiência",
    experienceDescription: "Compras, sistemas de gestão e indicadores no setor de transporte.",
    educationEyebrow: "Formação",
    educationTitle: "Base de negócio, formação técnica",
    educationDescription:
      "Curso Ciência da Computação e tenho formação concluída em Logística e MBA em Supply Chain Management.",
    certificationsEyebrow: "Certificações",
    certificationsTitle: "Estudo que levo para os projetos",
    certificationsDescription:
      "Os cursos complementam a prática em Excel, Power BI, Power Query e DAX e os estudos de SQL e inteligência artificial.",
    certificationsEmpty: "Nenhum certificado publicado nesta versão.",
    datanogsEyebrow: "Projeto autoral",
    datanogsTitle: "DataNogs",
    datanogsDescription:
      "Um espaço para compartilhar o que aprendo ao estudar e construir análises.",
    ctaEyebrow: "Próximo passo",
    ctaTitle: "Veja os cases ou fale comigo.",
    ctaDescription:
      "Escolha um projeto para conhecer os dados, os cálculos e as decisões de construção.",
    contactEyebrow: "Contato",
    contactTitle: "Vamos conversar?",
    contactChannels: "Ver canais de contato",
    analysisFlow: {
      label: "Estrutura de análise",
      steps: ["Fonte", "Tratamento", "Modelagem", "Análise", "Comunicação"],
      footer: "Processo antes de interface",
    },
  },
  experience: {
    activities: "Na rotina",
    dataWork: "No trabalho com dados",
  },
  about: {
    eyebrow: "Sobre",
    experienceEyebrow: "Trajetória",
    experienceTitle: "Experiência",
    educationEyebrow: "Formação",
    educationTitle: "Formação acadêmica",
    educationDescription:
      "Ciência da Computação amplia minha base técnica. Logística e Supply Chain complementam a compreensão das operações.",
    seeProjects: "Ver projetos",
  },
  certifications: {
    pageEyebrow: "Formação",
    pageTitle: "Formação e Certificações",
    pageDescription:
      "Curso Ciência da Computação e complemento a formação com estudos aplicados aos projetos de dados. Logística e o MBA em Supply Chain Management fazem parte da minha base de negócio.",
    academicLabel: "Formações acadêmicas",
    certificatesLabel: "Certificados",
    sourceLabel: "Documentos",
    sourceValue: "Certificados disponíveis em PDF.",
    libraryEyebrow: "Biblioteca",
    libraryTitle: "Certificações",
    libraryDescription:
      "Veja o que estudei e abra os certificados em PDF. Use a busca ou os filtros para encontrar um tema.",
    search: "Buscar",
    searchPlaceholder: "Curso, instituição, tecnologia ou tema",
    category: "Categoria",
    technology: "Tecnologia",
    all: "Todos",
    workload: "Duração",
    technologies: "Tecnologias",
    preview: "Visualizar",
    openPdf: "Abrir PDF",
    close: "Fechar visualização",
    clear: "Limpar filtros",
    empty: "Nenhum certificado encontrado. Tente outro termo ou limpe os filtros.",
    resultSingular: "certificado",
    resultPlural: "certificados",
    seeAll: "Ver formação e certificados",
  },
  projects: {
    eyebrow: "Portfólio",
    title: "Projetos e cases",
    featured: "Projeto em destaque",
    viewCase: "Ver case",
    coverPlaceholder: "Imagem de capa",
    coverAlt: "Capa do projeto",
    dashboardPlaceholder: "Imagem do dashboard principal",
    dashboardAlt: "Dashboard do projeto",
    libraryEyebrow: "Todos os projetos",
    libraryTitle: "Explore por categoria ou tecnologia",
    libraryDescription:
      "Escolha um tema e veja a pergunta, os dados e a construção de cada análise.",
    filterCategory: "Categoria",
    filterTechnology: "Tecnologia",
    filterAll: "Todos",
    resultSingular: "projeto",
    resultPlural: "projetos",
    clearFilters: "Limpar filtros",
    noResults: "Nenhum projeto com essa combinação. Limpe os filtros para ver todos.",
    ctaEyebrow: "Contato",
    ctaTitle: "Quer conversar sobre algum dos cases?",
    ctaDescription: "Fale comigo sobre os dados, as medidas ou as escolhas de cada relatório.",
  },
  project: {
    contents: "Neste case",
    back: "Todos os projetos",
    dashboard: "Dashboard público",
    heroPlaceholder: "Imagem principal do projeto",
    heroAlt: "Visão geral do projeto",
    context: "Contexto",
    problem: "Pergunta analítica",
    objective: "Objetivo",
    data: "Fontes e estrutura dos dados",
    dataSource: "Fonte dos dados",
    dataEntities: "Tabelas do modelo",
    dataFields: "Campos da base",
    treatment: "Tratamento",
    transformation: "Transformação",
    model: "Modelagem",
    metrics: "Métricas",
    tools: "Tecnologias",
    explore: "Dashboard",
    dashboardPages: "Páginas",
    gallery: "Galeria do relatório",
    openImage: "Abrir imagem",
    openDashboard: "Abrir no Power BI",
    insights: "O que a análise permite investigar",
    results: "O que foi construído",
    learnings: "Técnicas aplicadas",
    overview: "Visão do projeto",
    dataModel: "Dados e modelagem",
    viewFormula: "Ver fórmula DAX",
    observations: "Leitura do dashboard",
    challenges: "Escolhas e desafios",
    limitations: "Cuidados ao interpretar os dados",
    github: "GitHub",
    youtube: "YouTube",
    continue: "Continue",
    others: "Outros projetos",
  },
  datanogsPage: {
    identity: "Identidade",
    professional: "Identidade profissional",
    project: "Projeto autoral",
    distinction: "Os projetos e o processo de aprender",
    scope: "Temas",
    scopeTitle: "Dados e BI, com espaço para explorar",
    presence: "Presença digital",
    presenceTitle: "Onde acompanhar",
    presenceDescription:
      "YouTube para vídeo, GitHub para código e LinkedIn para contato profissional.",
    visit: "Acessar",
    portfolio: "Portfólio profissional",
    portfolioTitle: "Conheça os projetos em detalhe.",
    portfolioDescription:
      "Veja como organizei os dados, as medidas e os relatórios dos quatro projetos em Power BI.",
    professionalDescription:
      "É a identidade principal deste portfólio e da minha presença profissional.",
    viewProjects: "Ver projetos",
    contact: "Contato",
  },
  contact: {
    eyebrow: "Contato",
    title: "Vamos conversar?",
    open: "Abrir",
    copy: "Copiar",
    copied: "Copiado!",
    copyEmail: "Copiar e-mail",
    copyError: "Não foi possível copiar automaticamente. Selecione o endereço acima para copiar.",
  },
  footer: {
    navigation: "Navegação",
    channels: "Canais",
    lastUpdate: "Última atualização",
    pending: "link pendente",
    backToTop: "Voltar ao topo",
  },
  common: {
    pending: "link pendente",
    inProgress: "Conteúdo em desenvolvimento",
    profilePhotoAlt: "Retrato profissional de João Vittor Nogueira",
    opensNewTab: "abre em uma nova aba",
  },
  notFound: {
    title: "Página não encontrada",
    text: "A página que você procura não existe ou foi movida.",
    home: "Voltar ao início",
  },
  error: {
    title: "Esta página não carregou",
    text: "Algo deu errado. Tente novamente ou volte ao início.",
    retry: "Tentar novamente",
    home: "Voltar ao início",
  },
};
export type UiDict = typeof pt;
const en: UiDict = {
  nav: {
    about: "About",
    projects: "Projects",
    education: "Education",
    datanogs: "DataNogs",
    experience: "Experience",
    contact: "Contact",
    cta: "Let's talk",
    home: "home",
    main: "Main navigation",
    mobile: "Mobile navigation",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    skip: "Skip to content",
  },
  prefs: {
    language: "Language",
    theme: "Theme",
    toDark: "Switch to dark theme",
    toLight: "Switch to light theme",
    dark: "Dark",
    light: "Light",
    switchTo: "Switch language to",
  },
  home: {
    exploreProjects: "Explore projects",
    mainStack: "Core stack",
    studying: "Currently studying: SQL · Python",
    quickNav: "Explore my work",
    toolsLink: "Tools",
    aboutEyebrow: "About me",
    aboutTitle: "How I approach data",
    aboutLink: "More about me",
    stackEyebrow: "Tools",
    stackTitle: "From preparation to analysis",
    stackDescription:
      "Power Query prepares the data; the model and DAX measures support the analysis; Power BI presents it. Here is what I use in projects and what I am studying.",
    projectsEyebrow: "Portfolio",
    projectsTitle: "Selected work",
    featured: "Featured project",
    allProjects: "View all projects",
    experienceEyebrow: "Career",
    experienceTitle: "Experience",
    experienceDescription: "Purchasing, management systems and indicators in transportation.",
    educationEyebrow: "Education",
    educationTitle: "Business grounding, technical study",
    educationDescription:
      "I study Computer Science and hold a Technology Degree in Logistics and an MBA in Supply Chain Management.",
    certificationsEyebrow: "Certifications",
    certificationsTitle: "Learning I bring to projects",
    certificationsDescription:
      "Courses complement my work with Excel, Power BI, Power Query and DAX, and my studies in SQL and artificial intelligence.",
    certificationsEmpty: "No certificate has been published in this version.",
    datanogsEyebrow: "Personal project",
    datanogsTitle: "DataNogs",
    datanogsDescription: "A space to share what I learn while studying and building analyses.",
    ctaEyebrow: "Next step",
    ctaTitle: "Explore the case studies or get in touch.",
    ctaDescription: "Choose a project to explore the data, calculations and design choices.",
    contactEyebrow: "Contact",
    contactTitle: "Let’s talk",
    contactChannels: "See contact channels",
    analysisFlow: {
      label: "Analysis structure",
      steps: ["Source", "Transform", "Model", "Analyze", "Communicate"],
      footer: "Process before interface",
    },
  },
  experience: {
    activities: "Day-to-day work",
    dataWork: "Working with data",
  },
  about: {
    eyebrow: "About",
    experienceEyebrow: "Career",
    experienceTitle: "Experience",
    educationEyebrow: "Education",
    educationTitle: "Academic background",
    educationDescription:
      "Computer Science broadens my technical foundation. Logistics and Supply Chain support my understanding of operations.",
    seeProjects: "View projects",
  },
  certifications: {
    pageEyebrow: "Education",
    pageTitle: "Education & Certifications",
    pageDescription:
      "I study Computer Science and complement it with learning applied to data projects. My Logistics degree and MBA in Supply Chain Management provide business grounding.",
    academicLabel: "Academic programs",
    certificatesLabel: "Certificates",
    sourceLabel: "Documents",
    sourceValue: "Certificates available as PDFs.",
    libraryEyebrow: "Library",
    libraryTitle: "Certifications",
    libraryDescription:
      "See what I have studied and open the PDF certificates. Use search or filters to find a topic.",
    search: "Search",
    searchPlaceholder: "Course, institution, technology or topic",
    category: "Category",
    technology: "Technology",
    all: "All",
    workload: "Course hours",
    technologies: "Technologies",
    preview: "Preview",
    openPdf: "Open PDF",
    close: "Close preview",
    clear: "Clear filters",
    empty: "No certificates found. Try another search or clear the filters.",
    resultSingular: "certificate",
    resultPlural: "certificates",
    seeAll: "View education and certificates",
  },
  projects: {
    eyebrow: "Portfolio",
    title: "Projects and case studies",
    featured: "Featured project",
    viewCase: "View case study",
    coverPlaceholder: "Cover image",
    coverAlt: "Cover of project",
    dashboardPlaceholder: "Main dashboard image",
    dashboardAlt: "Dashboard of project",
    libraryEyebrow: "All projects",
    libraryTitle: "Explore by category or technology",
    libraryDescription:
      "Choose a topic and explore the question, data and work behind each analysis.",
    filterCategory: "Category",
    filterTechnology: "Technology",
    filterAll: "All",
    resultSingular: "project",
    resultPlural: "projects",
    clearFilters: "Clear filters",
    noResults: "No projects match this combination. Clear the filters to see all projects.",
    ctaEyebrow: "Contact",
    ctaTitle: "Want to discuss one of the case studies?",
    ctaDescription: "Ask me about the data, measures or choices behind a report.",
  },
  project: {
    contents: "In this case study",
    back: "All projects",
    dashboard: "Public dashboard",
    heroPlaceholder: "Main project image",
    heroAlt: "Overview of project",
    context: "Context",
    problem: "Analytical question",
    objective: "Goal",
    data: "Data sources and structure",
    dataSource: "Data source",
    dataEntities: "Model tables",
    dataFields: "Dataset fields",
    treatment: "Data preparation",
    transformation: "Transformation",
    model: "Modeling",
    metrics: "Metrics",
    tools: "Technologies",
    explore: "Dashboard",
    dashboardPages: "Pages",
    gallery: "Report gallery",
    openImage: "Open image",
    openDashboard: "Open in Power BI",
    insights: "What the analysis helps explore",
    results: "What I built",
    learnings: "Techniques used",
    overview: "Project overview",
    dataModel: "Data and modeling",
    viewFormula: "View DAX formula",
    observations: "Reading the dashboard",
    challenges: "Choices and challenges",
    limitations: "How to interpret the data",
    github: "GitHub",
    youtube: "YouTube",
    continue: "Keep exploring",
    others: "More projects",
  },
  datanogsPage: {
    identity: "Identity",
    professional: "Professional identity",
    project: "Personal project",
    distinction: "The projects and the learning process",
    scope: "Topics",
    scopeTitle: "Data and BI, with room to explore",
    presence: "Digital presence",
    presenceTitle: "Where to follow",
    presenceDescription:
      "YouTube for video, GitHub for code and LinkedIn for professional contact.",
    visit: "Visit",
    portfolio: "Professional portfolio",
    portfolioTitle: "Explore the projects in detail.",
    portfolioDescription:
      "See how I organized the data, measures and reports in the four Power BI projects.",
    professionalDescription:
      "It is the primary identity of this portfolio and my professional presence.",
    viewProjects: "View projects",
    contact: "Contact",
  },
  contact: {
    eyebrow: "Contact",
    title: "Let’s talk",
    open: "Open",
    copy: "Copy",
    copied: "Copied!",
    copyEmail: "Copy email",
    copyError: "Automatic copying is unavailable. Select the address above to copy it.",
  },
  footer: {
    navigation: "Navigation",
    channels: "Channels",
    lastUpdate: "Last updated",
    pending: "link pending",
    backToTop: "Back to top",
  },
  common: {
    pending: "link pending",
    inProgress: "Content in progress",
    profilePhotoAlt: "Professional portrait of João Vittor Nogueira",
    opensNewTab: "opens in a new tab",
  },
  notFound: {
    title: "Page not found",
    text: "The page you're looking for doesn't exist or has been moved.",
    home: "Back to home",
  },
  error: {
    title: "This page didn't load",
    text: "Something went wrong. Try again or head back home.",
    retry: "Try again",
    home: "Back to home",
  },
};
export const ui = { pt, en };
