/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DatanogsRouteImport } from './routes/datanogs'
import { Route as EnRouteImport } from './routes/en'
import { Route as FormacaoRouteImport } from './routes/formacao'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnDatanogsRouteImport } from './routes/en.datanogs'
import { Route as EnEducationRouteImport } from './routes/en.education'
import { Route as EnProjectsRouteImport } from './routes/en.projects'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'
import { Route as EnProjectsIndexRouteImport } from './routes/en.projects.index'
import { Route as EnProjectsSlugRouteImport } from './routes/en.projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DatanogsRoute = DatanogsRouteImport.update({
  id: '/datanogs',
  path: '/datanogs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const FormacaoRoute = FormacaoRouteImport.update({
  id: '/formacao',
  path: '/formacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnDatanogsRoute = EnDatanogsRouteImport.update({
  id: '/datanogs',
  path: '/datanogs',
  getParentRoute: () => EnRoute,
} as any)
const EnEducationRoute = EnEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => EnRoute,
} as any)
const EnProjectsRoute = EnProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => EnRoute,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsIndexRoute = EnProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnProjectsRoute,
} as any)
const EnProjectsSlugRoute = EnProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/datanogs': typeof DatanogsRoute
  '/en': typeof EnRouteWithChildren
  '/formacao': typeof FormacaoRoute
  '/sobre': typeof SobreRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/datanogs': typeof EnDatanogsRoute
  '/en/education': typeof EnEducationRoute
  '/en/projects': typeof EnProjectsRouteWithChildren
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/en/': typeof EnIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/en/projects/$slug': typeof EnProjectsSlugRoute
  '/en/projects/': typeof EnProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/datanogs': typeof DatanogsRoute
  '/formacao': typeof FormacaoRoute
  '/sobre': typeof SobreRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/datanogs': typeof EnDatanogsRoute
  '/en/education': typeof EnEducationRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/en': typeof EnIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/en/projects/$slug': typeof EnProjectsSlugRoute
  '/en/projects': typeof EnProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/datanogs': typeof DatanogsRoute
  '/en': typeof EnRouteWithChildren
  '/formacao': typeof FormacaoRoute
  '/sobre': typeof SobreRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/datanogs': typeof EnDatanogsRoute
  '/en/education': typeof EnEducationRoute
  '/en/projects': typeof EnProjectsRouteWithChildren
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/en/': typeof EnIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/en/projects/$slug': typeof EnProjectsSlugRoute
  '/en/projects/': typeof EnProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/datanogs'
    | '/en'
    | '/formacao'
    | '/sobre'
    | '/en/about'
    | '/en/contact'
    | '/en/datanogs'
    | '/en/education'
    | '/en/projects'
    | '/projetos/$slug'
    | '/en/'
    | '/projetos/'
    | '/en/projects/$slug'
    | '/en/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/datanogs'
    | '/formacao'
    | '/sobre'
    | '/en/about'
    | '/en/contact'
    | '/en/datanogs'
    | '/en/education'
    | '/projetos/$slug'
    | '/en'
    | '/projetos'
    | '/en/projects/$slug'
    | '/en/projects'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/datanogs'
    | '/en'
    | '/formacao'
    | '/sobre'
    | '/en/about'
    | '/en/contact'
    | '/en/datanogs'
    | '/en/education'
    | '/en/projects'
    | '/projetos/$slug'
    | '/en/'
    | '/projetos/'
    | '/en/projects/$slug'
    | '/en/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  DatanogsRoute: typeof DatanogsRoute
  EnRoute: typeof EnRouteWithChildren
  FormacaoRoute: typeof FormacaoRoute
  SobreRoute: typeof SobreRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datanogs': {
      id: '/datanogs'
      path: '/datanogs'
      fullPath: '/datanogs'
      preLoaderRoute: typeof DatanogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formacao': {
      id: '/formacao'
      path: '/formacao'
      fullPath: '/formacao'
      preLoaderRoute: typeof FormacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/datanogs': {
      id: '/en/datanogs'
      path: '/datanogs'
      fullPath: '/en/datanogs'
      preLoaderRoute: typeof EnDatanogsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/education': {
      id: '/en/education'
      path: '/education'
      fullPath: '/en/education'
      preLoaderRoute: typeof EnEducationRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/projects': {
      id: '/en/projects'
      path: '/projects'
      fullPath: '/en/projects'
      preLoaderRoute: typeof EnProjectsRouteImport
      parentRoute: typeof EnRoute
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects/': {
      id: '/en/projects/'
      path: '/'
      fullPath: '/en/projects/'
      preLoaderRoute: typeof EnProjectsIndexRouteImport
      parentRoute: typeof EnProjectsRoute
    }
    '/en/projects/$slug': {
      id: '/en/projects/$slug'
      path: '/$slug'
      fullPath: '/en/projects/$slug'
      preLoaderRoute: typeof EnProjectsSlugRouteImport
      parentRoute: typeof EnProjectsRoute
    }
  }
}

interface EnProjectsRouteChildren {
  EnProjectsSlugRoute: typeof EnProjectsSlugRoute
  EnProjectsIndexRoute: typeof EnProjectsIndexRoute
}

const EnProjectsRouteChildren: EnProjectsRouteChildren = {
  EnProjectsSlugRoute: EnProjectsSlugRoute,
  EnProjectsIndexRoute: EnProjectsIndexRoute,
}

const EnProjectsRouteWithChildren = EnProjectsRoute._addFileChildren(
  EnProjectsRouteChildren,
)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnContactRoute: typeof EnContactRoute
  EnDatanogsRoute: typeof EnDatanogsRoute
  EnEducationRoute: typeof EnEducationRoute
  EnProjectsRoute: typeof EnProjectsRouteWithChildren
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnContactRoute: EnContactRoute,
  EnDatanogsRoute: EnDatanogsRoute,
  EnEducationRoute: EnEducationRoute,
  EnProjectsRoute: EnProjectsRouteWithChildren,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  DatanogsRoute: DatanogsRoute,
  EnRoute: EnRouteWithChildren,
  FormacaoRoute: FormacaoRoute,
  SobreRoute: SobreRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
